spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

scheduler:
  daily-report:
    cron: ${SCHEDULER_DAILY_REPORT_CRON}

kafka:
  topic: ${KAFKA_TOPIC_NAME}
server:
  port: 8083

services-url:
  auth-url: ${AUTH_SERVICE_URL}
  task-url: ${TASK_SERVICE_URL}

internal:
  api-key: ${INTERNAL_API_KEY}
  header-name: ${INTERNAL_NAME_HEADER}

