internal:
  api-key: ${INTERNAL_API_KEY}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

Kafka:
  topic: ${KAFKA_TOPIC_NAME}
server:
  port: 8083

services:
  auth-url: ${AUTH_SERVICE_URL}
  task-url: ${TASK_SERVICE_URL}